application: photoblog-1008
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin/.*
  script: _go_app
  login: admin
- url: /profile/.*
  script: _go_app
  login: required
- url: /.*
  script: _go_app
